### ISSUE TITLE
setState with function: Do we really need the `useCallback`?

### ISSUE THREAD

**Issue by alexilyaev** [500tech/hook-cook-book#1]
https://codesandbox.io/s/w6xynq3z9l

```js
function App() {
  const [count, setCount] = useState(1);
  const increment = useCallback(() => setCount(val => val + 1), []);

  return (
    <div className="App">
      <h1>Hello CodeSandbox {count}</h1>
      <button onClick={increment}>Increment</button>
    </div>
  );
}
```

Looks like we're creating the arrow function every render any way, so wrapping it in `useCallback` doesn't really help us with memory management.
Meaning, if we don't use `useCallback`, we re-define it on every render and JS will GC the older one. But with `useCallback` JS will still need to GC the new one.

Unless we're considering what React does with the function passed to `onClick`.
Does React add an actual event listener for each element we add `onClick` on?
I was under the impression that it uses Event Delegation and keeps it's own registry.
But looking at DevTools it does seem like there's an added event listener...
![image](https://user-images.githubusercontent.com/480469/74594756-8228d880-5042-11ea-8377-fa9399142900.png)

If it does add an event listener, will it remove the old one and set a new one when it receives a new function in the VDOM?
If that's the case then `useCallback` makes sense. Though I wouldn't want to start writing all of my code like that.

**Comment by adamkleingit** [comment]
Fixed
